apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-nexus
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-nexus
  template:
    metadata:
      labels:
        app: genai-nexus
    spec:
      containers:
      - name: genai-nexus
        image: k8snewacr.azurecr.io/genai-nexus:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: genai-nexus
  namespace: spring-petclinic
spec:
  selector:
    app: genai-nexus
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
